# ref https://www.innokrea.com/dockerizing-the-frontend-do-it-right-with-react-js-vite/ for vite

services:
  frontend-dev:
    build:
      context: ./
      dockerfile: Dockerfile 
      target: client-dev     
    ports:
      - "5173:5173"          
    volumes:
      - ./client:/usr/local/app/client  
      - /usr/local/app/client/node_modules
    stdin_open: true          
    tty: true                 

  backend-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/local/app/backend
      - /usr/local/app/backend/node_modules
    stdin_open: true          
    tty: true                 

  postgres:
    image: postgres
    container_name: mobile_postgres
    environment:
      POSTGRES_USER: justin
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  # frontend-prod:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     target: client-production  # Use the production stage
  #   ports:
  #     - "80:80"  # Serve on port 80 (standard for HTTP)
  #   environment:
  #     - NODE_ENV=production

  # backend-prod:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     target: backend-production
  #   ports:
  #     - 5001:5000  # Map port 5001 on host to port 5000 in the container
  #   environment:
  #     - NODE_ENV=production