# ref https://www.innokrea.com/dockerizing-the-frontend-do-it-right-with-react-js-vite/ for vite

services:
  frontend-dev:
    build:
      context: ./
      dockerfile: Dockerfile  # The Dockerfile for the frontend
      target: client-dev      # Use the client-dev stage from the Dockerfile
    ports:
      - "5173:5173"           # Expose Vite's default port (adjust if necessary)
    volumes:
      - ./client:/usr/local/app/client  # Mount your local client directory for live reload
      - /usr/local/app/client/node_modules
    stdin_open: true          # Keep STDIN open for running commands if necessary
    tty: true                 # Allocate a pseudo-TTY for terminal interaction (useful in dev)

  backend-dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/local/app/backend
      - /usr/local/app/backend/node_modules
    stdin_open: true          
    tty: true                 



  frontend-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      target: client-production  # Use the production stage
    ports:
      - "80:80"  # Serve on port 80 (standard for HTTP)
    environment:
      - NODE_ENV=production

  backend-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      target: backend-production
    ports:
      - 5001:5000  # Map port 5001 on host to port 5000 in the container
    environment:
      - NODE_ENV=production