services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  # The Dockerfile for the frontend
      target: client-dev      # Use the client-dev stage from the Dockerfile
    ports:
      - "5173:5173"           # Expose Vite's default port (adjust if necessary)
    volumes:
      - ./client:/usr/local/app/client  # Mount your local client directory for live reload
    environment:
      - NODE_ENV=development  # Set the environment for development
    stdin_open: true          # Keep STDIN open for running commands if necessary
    tty: true                 # Allocate a pseudo-TTY for terminal interaction (useful in dev)

